language: java
jdk:
- oraclejdk8
after_success:
- "./gradlew cobertura coveralls"
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: http4k-contract-todo-backend
  api_key:
    secure: dhyhgHxVubTlpzzKiPhP+KzROTzPdZoscPFJ+xDjJ8L+iKAcxCL3XPnjrkYZAJU78OrJpGgZb6x53EntHjZdqPGP7GOgxf5INSuo728rafDoNxuST0/32X9K4VNkbt/dbWlF1vL4A5oAe8HdKLKLOB+b82aFcFGFLeNLkXbYbEYd8yGVCqZ9e81XXcMfGQfDylE07EvOxzJJ0T/AQ9oA6uzAsQjg6STsGpZ+ug9RgKqXOxmnEO7bT8A/DGoCuFZY2VaSV/S5x8YiUnIDB0hB//XAAWJjYDpXre1V+T6wK7ro0ikiPTY3/qXbCq0WxYn0NOGl1vFYuAaHTpKX5rGEWE/dYV4I61wKPvYqb6o01Vey84dCJL9CATNDe+oDriAS1YAZPMd0rxSZ9rgmAEnzDEXUte82mP/5dvL5gj1avJ+m6xTB42puRxii6xwBn+y7hBj+we3/KMc30p/b9iRJhuHaZXoVGUdeHAZUZ/pW6zpazG2B2WZvA9ZIk7gYEEz3G4LLD3Z7x+8//3mcZqA3NAPL2PHf9RDI+Ee9AfJwTwRTndkYPkMXjLPOVjU2pYwxC+tG+VhSiR/e8FEWlC33l5rV0kq02WlfirxYdd+B0NjQEwiFqaUPqUqhOLJgZaM32pzBNfN7bVZj+dOKMEqee6LpF+mQovCCi/HmJAhHthE=
